### ISSUE TITLE
Assorted TODO

### ISSUE THREAD

**Issue by XhmikosR** [siddharthkp/bundlesize#345]
Here's a few things I'd personally like fixed (the order might matter for some things):

- [ ] Make it clear which Node.js versions are supported. CI fails for Node.js 6, but it seems it's a devDependency issue. Either way, we need to clear this up and make sure whatever CI we use runs on all supported Node.js versions
- [ ] We need lock files for both core and store
- [ ] We need to enable security alerts in the repo settings
- [ ] We need dependabot enabled for security issues on the repo in `https://github.com/siddharthkp/bundlesize/network/alerts`
- [ ] We need to remove the unused/old greenkeeper branches from the repo
- [ ] We need to enable "Automatically delete head branches" repo option
- [ ] Enforce 2fa for all people with push rights on the repo
- [ ] Enforce 2fa on npm too for people with push rights
- [ ] Revisit third-party hooks and integrations and remove any unused ones
